# router.py

def route_query(query):
    """
    Route the user query to the appropriate handler based on the query content.
    
    Parameters:
        query (str): The user's query to be routed.
        
    Returns:
        str: The response generated by the appropriate handler.
    """
    query = query.lower()

    # Route to knowledge base handler if the query contains specific keywords
    if any(keyword in query for keyword in ['knowledge', 'info', 'detail']):
        response = handle_knowledge_base_query(query)
    else:
        response = handle_general_query(query)
    
    return response

def handle_knowledge_base_query(query):
    """
    Handle queries related to the knowledge base.
    
    Parameters:
        query (str): The user's query to be handled.
        
    Returns:
        str: The response retrieved from the knowledge base.
    """
    from models import get_knowledge_base_response
    response = get_knowledge_base_response(query)
    return response

def handle_general_query(query):
    """
    Handle general queries that are not related to the knowledge base.
    
    Parameters:
        query (str): The user's query to be handled.
        
    Returns:
        str: The response generated by the generative AI model.
    """
    from models import generate_response
    response = generate_response(query)
    return response

